# Generated by Django 5.0.6 on 2024-05-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='sumary',
            new_name='summary',
        ),
    ]
